### ISSUE TITLE
Feature: User can view a dad joke

### ISSUE THREAD

**Issue by Raphael-Cruzado** [moamel-hashim/dad-jokes#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/57853350/200671963-a5427210-4960-4c8d-9f81-9acf1e254331.png)
![image](https://user-images.githubusercontent.com/57853350/200672006-502d9012-6e79-4fe0-b253-4070aa1474ce.png)
![image](https://user-images.githubusercontent.com/57853350/200672034-84f12ebd-f77a-452c-9735-993d24ca0426.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Create UI
- [ ] Database NA

### ☁️ Server Tasks

- [ ] NA

### ⚡ Client Tasks

- [ ] Create few components for the client folder
- [ ] Edit the home page
- [ ] fetch to view a dad joke frpm API

### 🧑‍⚕️ Clean Up Tasks

NA yet
